export const GET_HISTORICAL_EVENTS = 'GET_HISTORICAL_EVENTS';
export const GET_LAUNCH_EVENTS = 'GET_LAUNCH_EVENTS';
export const GET_EVENT_ERROR = 'GET_EVENT_ERROR';
export const GET_SINGLE_LAUNCH = 'GET_SINGLE_LAUNCH';
export const GET_SINGLE_HISTORICAL = 'GET_SINGLE_HISTORICAL';
